name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      id: docker_build
      env:
       # Convertim numele repositoriului din litere mari in mici
       NUME_REPO: ${{ github.repository }}
      run: |
        IMAGE_NAME="ghcr.io/$(echo $NUME_REPO | tr '[:upper:]' '[:lower:]')/traversarea_arb_avl"
        docker build . --file Dockerfile --tag $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
